# Generated by Django 5.2.4 on 2025-07-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tokenholding',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('lottery_created', 'Tirage créé'), ('lottery_executed', 'Tirage exécuté'), ('winner_selected', 'Gagnant sélectionné'), ('payout_sent', 'Gain envoyé'), ('jackpot_updated', 'Jackpot mis à jour'), ('system_error', 'Erreur système'), ('wallet_connected', 'Portefeuille connecté'), ('wallet_synced', 'Portefeuille synchronisé'), ('bulk_sync_triggered', 'Synchronisation en masse déclenchée'), ('bulk_sync_completed', 'Synchronisation en masse terminée'), ('system_sync_triggered', 'Synchronisation système déclenchée'), ('config_updated', 'Configuration mise à jour'), ('bulk_sync', 'Synchronisation en masse')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tokenholding',
            name='wallet_address',
            field=models.CharField(db_index=True, max_length=44, unique=True),
        ),
    ]
